#!/bin/bash

[ "$#" -ne 1 ] && echo "usage: $0 <target-branch>" && exit 1

TARGET=$1
LABELS=sync

for PR_NUMBER in $(gh pr list -l "${LABELS}" -S "in:title ${PREFIX}" --json number -q '.[].number'); do
   pr_sha=$(gh pr view $PR_NUMBER --json title -q '.title' | sed 's/.*://'| tr -d ' ')
   echo "cleanup $PR_NUMBER; sha: $pr_sha"
   if git log -n1 --oneline "$pr_sha" ;then
     base=$(git merge-base origin/${TARGET} ${pr_sha})
     if [ "$base" == "$pr_sha" ]; then
       gh pr close "$PR_NUMBER" --comment "Content was already merged." --delete-branch
     fi
   fi
done
