#!/bin/bash

[ "$PREFIX" == "" ] && echo "PREFIX is unset: its used as the branch and pr title prefix" && exit 1
[ "$TARGET" == "" ] && echo "TARGET is unset: it must be the target branch" && exit 1
[ "$LABELS" == "" ] && echo "LABELS is unset: it must be a list of labels for the sync PRs" && exit 1

for PR_NUMBER in $(gh pr list -l "${LABELS}" -S "in:title ${PREFIX}" --json number -q '.[].number'); do
   pr_sha=$(gh pr view $PR_NUMBER --json title -q '.title' | sed 's/.*://'| tr -d ' ')
   echo "cleanup $PR_NUMBER; sha: $pr_sha"
   if git log -n1 --oneline "$pr_sha" ;then
     base=$(git merge-base origin/${TARGET} ${pr_sha})
     if [ "$base" == "$pr_sha" ]; then
       gh pr close "$PR_NUMBER" --comment "Content was already merged." --delete-branch
     fi
   fi
done
