#!/bin/bash

LABELS=sync

[ "$1" == "--denoise" ] && denoise=1 && shift
[ "$#" -ne 3 ] && echo "usage: $0 [--denoise] <target-branch> <ref> <prefix>" && exit 1

set -e
set -x

TARGET=$1
REF=$2
PREFIX=$3

cnt=$(gh pr list -S "in:title $REF" | tee >(cat >&2) | wc -l)
if [ "$cnt" != 0 ];then
  echo "@ PR already exists for $REF"
  exit 0
fi

pr_branch="${PREFIX}-${last_sha}"

git checkout -b "${pr_branch}" ${REF}

if [ "$denoise" != 0 ];then
  echo "@ denoise enabled."
  if git merge "origin/${TARGET}"; then
    echo "@ denoised: merge commit"
  else
    echo "@ denoised: empty commit"
    git merge --abort
    git commit --allow-empty -m "Forced empty commit to denoise branches"
  fi
fi

git push -u origin "${pr_branch}"
gh pr create -B "${INPUT_BRANCH}" -H "${pr_branch}" -l "${LABELS}" -t "$PREFIX: ${REF}"

