name: Auto approve

on: pull_request_target

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    ##if: github.event.issue.user.login == 'kgyrtkirk'
    steps:
      - uses: hmarr/auto-approve-action@v4
      - run: gh pr merge --auto -m
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

