name: Build / Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build

  trigger-deploy:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() && github.event_name == 'push' }}
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - run: |
       set -ex
       git merge --ff-only x-deploy
       git tag -f x-deploy
       git push origin -f x-deploy
