name: Pull upstream
on:
  #schedule:
  #  # * is a special character in YAML so you have to quote this string
  #  - cron:  '* * * * *'
  workflow_dispatch:
jobs:
  pull_upstream:
    runs-on: ubuntu-latest
    env:
      PREFIX: sync/main
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
    - name: add upstream
      run: |
        gh pr list
        git remote add upstream https://github.com/kgyrtkirk/checkstyle-plugins
        git fetch upstream
        gh pr list
    - run: |
        REF=`git rev-parse upstream/main`
        .github/scripts/sync_open_pr --denoise main $REF "$PREFIX: $REF"
    - run: |
        .github/scripts/sync_cleanup "$PREFIX"
