name: Pull upstream
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'
  workflow_dispatch:
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: kgyrtkirk/github-action-sync@master
      with:
        upstream: https://github.com/kgyrtkirk/checkstyle-plugins
        upstream_branch: upstream
        branch: main
        pr_labels: upstream
        pr_title: this->that
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        GITBOT_EMAIL: vasarlas.git@rxd.hu
        DRY_RUN: false

