name: Pull upstream
on:
  #schedule:
  #  # * is a special character in YAML so you have to quote this string
  #  - cron:  '* * * * *'
  workflow_dispatch:
jobs:
  pull_upstream:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: kgyrtkirk/github-action-sync@denoise
      with:
        upstream: https://github.com/kgyrtkirk/checkstyle-plugins
        upstream_branch: upstream
        branch: main
        pr_labels: upstream
        pr_title: this->that
        sync_branch_prefix: sync/this/that
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        GITBOT_EMAIL: vasarlas.git@rxd.hu
        DRY_RUN: false

  main2:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch
      uses: kgyrtkirk/github-action-sync@denoise
      with:
        upstream: https://github.com/z901/checkstyle-plugins
        upstream_branch: main
        branch: main2
        pr_labels: upstream
        pr_title: main->main2
        sync_branch_prefix: sync/m2
        denoise_message: 'Forced empty commit to denoise branches'
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        GITBOT_EMAIL: vasarlas.git@rxd.hu
        DRY_RUN: false

